AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '**/*.gemspec'
    - '**/vendor/**/*'
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - app/helpers/application_helper.rb
    - app/helpers/devise_helper.rb
    - '**/db/**/*'
    - '**/config/**/*'
    - '**/bin/**/*'

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - "config/unicorn/*"
    - "lib/tasks/live_test.rake"

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Max: 120
  Exclude:
    - "config/initializers/devise.rb"
    - "config/initializers/spree.rb"

Metrics/MethodLength:
  Max: 20

Style/ClassAndModuleChildren:
  Exclude:
    - "app/controllers/**/*" # We generally use compact style here

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    # These are naturally DSL-y, and so let's be lenient.
    - "spec/**/*"
    - "lib/tasks/**/*.rake"

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Layout/SpaceBeforeFirstArg:
  Exclude:
    # We often add extra spaces for alignment in factories.
    - "spec/factories/*"

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrivialAccessors:
  ExactNameMatch: true

Layout/IndentArray:
  EnforcedStyle: consistent

Style/NumericLiterals:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"

Bundler/OrderedGems:
  Enabled: false

# Overrides can go here, but try to conform to standards when possible.
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_decorator.rb"
    - "spec/**/*_spec.rb"
    - "spec/factories/*.rb"
    - "config/routes.rb" # we have a lot of routes. tough shit.
